# Zero Trust Spring Boot Application Configuration
server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: zero-trust-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  # Nueva sintaxis para Spring Boot 3.x
  config:
    import: "vault://secret/zero-trust-app"

  # Configuración de Vault
  cloud:
    vault:
      enabled: true
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      token: ${VAULT_TOKEN:dev-root-token}
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: zero-trust-app

  # Base de datos por defecto (H2)
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

# Configuración JWT usando Vault
app:
  jwt:
    secret: ${vault.secret.jwt.secret:zero-trust-default-secret-key-change-in-production-must-be-at-least-64-characters}
    access-token-duration: PT15M
    refresh-token-duration: P7D
    issuer: zero-trust-app
    enable-refresh-token-rotation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      show-details: when-authorized

# Debug logging HABILITADO
logging:
  level:
    com.example.zerotrust: DEBUG
    org.springframework: INFO
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.boot.context.config: DEBUG

---
spring:
  config:
    activate:
      on-profile: test

  # Vault deshabilitado en tests para simplicidad
  cloud:
    vault:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: false

# JWT usando valores por defecto en tests
app:
  jwt:
    secret: zero-trust-test-secret-key-must-be-at-least-64-characters-long-for-tests
    access-token-duration: PT15M
    refresh-token-duration: P7D
    issuer: zero-trust-app
    enable-refresh-token-rotation: true

---
spring:
  config:
    activate:
      on-profile: production
    import: "vault://secret/zero-trust-app"

  # Vault configuration para producción
  cloud:
    vault:
      enabled: true
      host: vault
      port: 8200
      scheme: http
      token: ${VAULT_TOKEN}
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: zero-trust-app

  # Base de datos PostgreSQL usando secretos de Vault
  datasource:
    url: jdbc:postgresql://${vault.secret.database.host:localhost}:${vault.secret.database.port:5432}/${vault.secret.database.name:zerotrust}
    username: ${vault.secret.database.username:zerotrust}
    password: ${vault.secret.database.password:secure_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  h2:
    console:
      enabled: false

# JWT usando secretos de Vault en producción
app:
  jwt:
    secret: ${vault.secret.jwt.secret}
    access-token-duration: PT15M
    refresh-token-duration: P7D
    issuer: zero-trust-app
    enable-refresh-token-rotation: true

server:
  ssl:
    enabled: false  # Configurar en producción real

# Logging más restrictivo en producción
logging:
  level:
    com.example.zerotrust: INFO
    org.springframework: WARN
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
