# Configuración de la aplicación Zero Trust
app:
  jwt:
    # Emisor del token JWT
    issuer: "zero-trust-service"

    # Duración de tokens
    access-token-duration: PT15M      # 15 minutos
    refresh-token-duration: P7D       # 7 días

    # Rotación de refresh tokens
    enable-refresh-token-rotation: true

    # Algoritmo de firma
    signing-algorithm: "HS256"

    # Tiempo de gracia para validación (clock skew)
    clock-skew: PT1M                  # 1 minuto

    # Audiencia del token
    audience: "zero-trust-clients"

    # Configuración del header
    token-prefix: "Bearer "
    token-header: "Authorization"

    # Límites de seguridad
    max-active-tokens-per-user: 5

    # Blacklist de tokens
    enable-token-blacklist: true
    blacklist-ttl: P30D               # 30 días

# Configuración de Spring Boot
spring:
  application:
    name: zero-trust-spring-boot

  # Base de datos
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Console (solo para desarrollo)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Redis (para cache y blacklist)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.jwt.issuer}

# Configuración de logs
logging:
  level:
    com.example.zerotrust: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Información de la aplicación
info:
  app:
    name: ${spring.application.name}
    description: "Enterprise-grade Zero Trust security implementation"
    version: "1.0.0"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"

---
# Perfil de desarrollo
spring:
  config:
    activate:
      on-profile: dev

  # Base de datos H2 persistente para desarrollo
  datasource:
    url: jdbc:h2:file:./data/zero-trust-dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.zerotrust: DEBUG
    org.springframework.security: DEBUG

---
# Perfil de testing
spring:
  config:
    activate:
      on-profile: test

  # Base de datos en memoria para tests
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

app:
  jwt:
    # Tokens más cortos para tests
    access-token-duration: PT5M       # 5 minutos
    refresh-token-duration: PT1H      # 1 hora

logging:
  level:
    com.example.zerotrust: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

---
# Perfil de producción
spring:
  config:
    activate:
      on-profile: production

  # PostgreSQL para producción
  datasource:
    url: jdbc:postgresql://localhost:5432/zerotrust_prod
    username: ${DB_USERNAME:zerotrust_user}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Redis para producción
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # Security adicional para producción
  h2:
    console:
      enabled: false

app:
  jwt:
    secret: "mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    secret-from-vault: false
    # Configuración segura para producción
    issuer: ${JWT_ISSUER:zero-trust-prod}
    access-token-duration: ${JWT_ACCESS_DURATION:PT15M}
    refresh-token-duration: ${JWT_REFRESH_DURATION:P7D}
    enable-refresh-token-rotation: true

logging:
  level:
    com.example.zerotrust: INFO
    org.springframework: WARN
  file:
    name: ./logs/zero-trust-application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics