# Zero Trust Spring Boot Application Configuration
server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

spring:
  application:
    name: zero-trust-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  # Base de datos por defecto (H2)
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: false

logging:
  level:
    com.example.zerotrust: WARN
    org.springframework: WARN

---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:zerotrust}
    username: ${DB_USERNAME:zerotrust}
    password: ${DB_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  h2:
    console:
      enabled: false

server:
  ssl:
    enabled: false  # Configurar en producción real
