spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false

logging:
  level:
    com.example.zerotrust: DEBUG
    org.springframework.boot: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  security:
    jwt:
      secret: test-secret-key-only-for-testing
    risk:
      high-threshold: 1.0
